
version: '3.5'

services:
  back-end:
    build:
      context: codes/back-end 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always

  front-end:
    build:
      context: codes/front-end
      dockerfile: Dockerfile
    volumes:
      - './codes/front-end:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - back-end

